apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namePrefix: prod-

resources:
- ../../base

commonLabels:
  variant: production

# ref: https://tech.aabouzaid.com/2022/11/set-openapi-patch-strategy-for-kubernetes-custom-resources-kustomize.html
# openapi:
#   path: cr-openapi-schema.json

patchesStrategicMerge:
  - "ol-app-patch.yaml"

# patches:
# - patch: |-
#     - op: replace
#       path: /spec/applicationImage
#       value: quay.io/rafaeltuelho/openliberty-starter-app:latest
#   target:
#     kind: OpenLibertyApplication
